# Generated by Django 4.1.6 on 2023-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("tier1", "Tier 1"),
                    ("tier2", "Tier 2"),
                    ("tier3", "Tier 3"),
                    ("admin", "Admin"),
                ],
                max_length=7,
            ),
        ),
    ]
