# Generated by Django 4.2.6 on 2023-11-29 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_code', models.IntegerField()),
                ('area_name', models.CharField(max_length=255)),
                ('tier2_officer', models.OneToOneField(db_column='tier2_officer', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_code', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('consumer_number', models.IntegerField(primary_key=True, serialize=False)),
                ('city_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consumer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tier2Tier3Relationship',
            fields=[
                ('tier3_officer', models.OneToOneField(db_column='tier3_officer', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tier2_tier3_relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsumptionHistory',
            fields=[
                ('consumer_number', models.OneToOneField(db_column='consumer_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.consumer')),
                ('time', models.DateTimeField()),
                ('consumption', models.FloatField()),
            ],
            options={
                'db_table': 'consumption_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fraud',
            fields=[
                ('consumer_number', models.OneToOneField(db_column='consumer_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.consumer')),
                ('fraud_status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fraud',
                'managed': False,
            },
        ),
    ]
