# Generated by Django 4.2.6 on 2023-12-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area_city_consumer_tier2tier3relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidStatus',
            fields=[
                ('tier3_officer', models.OneToOneField(db_column='tier3_officer', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.tier2tier3relationship')),
                ('consumer_number', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('raid_status', models.CharField(blank=True, max_length=10, null=True)),
                ('is_defaulter', models.CharField(blank=True, max_length=3, null=True)),
                ('image_id', models.CharField(blank=True, max_length=255, null=True)),
                ('raid_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raid_status',
                'managed': False,
            },
        ),
    ]
